[tool.poetry]
name = "tok715-cameron"
version = "0.1.0"
description = "monolith application for tok715/cameron artificial intelligence"
authors = ["GUO YANKE <hi@guoyk.xyz>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
